FROM houdini-base

COPY setup_hserver.sh /root/
RUN chmod +x /root/setup_hserver.sh

COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements_app.txt

# Run Flask server
CMD ["/bin/bash", "-c", "source /root/setup_hserver.sh && gunicorn --bind 0.0.0.0:8000 server:app -k eventlet"]