FROM houdini-base

COPY setup_hserver.sh /root/
RUN chmod +x /root/setup_hserver.sh

COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements_app.txt

# Expose the Flask port
EXPOSE 8080

# Run Flask server
CMD ["/bin/bash", "-c", "source /root/setup_hserver.sh && flask run --host=0.0.0.0 --port=8000"]